### ISSUE TITLE
Database error when trying to archive a project when Available

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#1001]
Tester:
```
Error met when I tried archiving a “Available“ project
dds project status archive -p ngis00025
ERROR    An Error occured: The system encountered an error in the database.
```

**Comment by MatthiasZepper** [comment]
Can't reproduce the issue at the moment, neither for a project with files nor for an empty project. 
```
root@da36eb091f01:/code# dds project status display -p someunit00001
     ︵
 ︵ (  )   ︵
(  ) ) (  (  )   SciLifeLab Data Delivery System
 ︶  (  ) ) (    http://dds_backend:5000/
      ︶ (  )    Version 0.0.10
          ︶
Current user: unituser_1
Current status of someunit00001: Available with deadline Mon, 06 Jun 2022 23:59:59 UTC
root@da36eb091f01:/code# dds project status archive -p someunit00001
     ︵
 ︵ (  )   ︵
(  ) ) (  (  )   SciLifeLab Data Delivery System
 ︶  (  ) ) (    http://dds_backend:5000/
      ︶ (  )    Version 0.0.10
          ︶
Current user: unituser_1
Project someunit00001 updated to status Archived
All files in someunit00001 deleted.
```
Do we have any more information available, e.g. the corresponding log entry and full error message?

**Comment by inaod568** [comment]
@MatthiasZepper No this is all we have. I can check if if happens for me and in that case I'll close it

**Comment by MatthiasZepper** [comment]
I think I could locate the corresponding error messages in the log. If I am not mistaken, deletion of the project's bucket failed and this prevented the project to be archived?

So I guess we should catch this exception and issue a better error message?

```
[2022-03-01 15:13:25,118] errors [WARNING] Project cannot be archived from this status but can be aborted if it has ever been made available
[2022-03-01 15:13:51,146] errors [WARNING] An error occurred (404) when calling the HeadBucket operation: Not Found
[2022-03-01 15:13:51,146] project [ERROR] 500 Internal Server Error: An error occurred (404) when calling the HeadBucket operation: Not Found
[2022-03-01 15:13:51,148] errors [ERROR] Server Error: Status was not updated
[2022-03-01 15:13:51,151] app [ERROR] Exception on /api/v1/proj/status [POST]
```

```
[2022-03-01 15:13:25,118] errors [WARNING] Project cannot be archived from this status but can be aborted if it has ever been made available
[2022-03-01 15:13:51,146] errors [WARNING] An error occurred (404) when calling the HeadBucket operation: Not Found
[2022-03-01 15:13:51,146] project [ERROR] 500 Internal Server Error: An error occurred (404) when calling the HeadBucket operation: Not Found
Traceback (most recent call last):
  File "/code/dds_web/api/dds_decorators.py", line 139, in check_bucket_exists
    self.resource.meta.client.head_bucket(Bucket=self.bucketname)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadBucket operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/dds_web/api/project.py", line 161, in post
    removed = RemoveContents().delete_project_contents(project=project)
  File "/code/dds_web/api/project.py", line 396, in delete_project_contents
    s3conn.remove_all()
  File "/code/dds_web/api/dds_decorators.py", line 141, in check_bucket_exists
    raise BucketNotFoundError(message=str(err))
dds_web.errors.BucketNotFoundError: 500 Internal Server Error: An error occurred (404) when calling the HeadBucket operation: Not Found
--
Traceback (most recent call last):
  File "/code/dds_web/api/dds_decorators.py", line 139, in check_bucket_exists
    self.resource.meta.client.head_bucket(Bucket=self.bucketname)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadBucket operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/dds_web/api/project.py", line 161, in post
    removed = RemoveContents().delete_project_contents(project=project)
  File "/code/dds_web/api/project.py", line 396, in delete_project_contents
    s3conn.remove_all()
  File "/code/dds_web/api/dds_decorators.py", line 141, in check_bucket_exists
    raise BucketNotFoundError(message=str(err))
dds_web.errors.BucketNotFoundError: 500 Internal Server Error: An error occurred (404) when calling the HeadBucket operation: Not Found
[2022-03-01 15:13:51,148] errors [ERROR] Server Error: Status was not updated
[2022-03-01 15:13:51,151] app [ERROR] Exception on /api/v1/proj/status [POST]
Traceback (most recent call last):
  File "/code/dds_web/api/dds_decorators.py", line 139, in check_bucket_exists
    self.resource.meta.client.head_bucket(Bucket=self.bucketname)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadBucket operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/dds_web/api/project.py", line 161, in post
    removed = RemoveContents().delete_project_contents(project=project)
  File "/code/dds_web/api/project.py", line 396, in delete_project_contents
    s3conn.remove_all()
  File "/code/dds_web/api/dds_decorators.py", line 141, in check_bucket_exists
    raise BucketNotFoundError(message=str(err))
dds_web.errors.BucketNotFoundError: 500 Internal Server Error: An error occurred (404) when calling the HeadBucket operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/code/dds_web/api/dds_decorators.py", line 158, in wrapper_logging_bind_request
    value = func(*args, **kwargs)
  File "/code/dds_web/api/dds_decorators.py", line 65, in verify_json
    return func(*args, **kwargs)
  File "/code/dds_web/api/dds_decorators.py", line 46, in handle_error
    result = func(*args, **kwargs)
  File "/code/dds_web/api/project.py", line 179, in post
    raise DatabaseError(message="Server Error: Status was not updated")
dds_web.errors.DatabaseError: 500 Internal Server Error: The system encountered an error in the database.


```

**Comment by inaod568** [comment]
Should be fixed. It was the project error - not creating the buckets etc.
